name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            baraziza/bookie:latest
            baraziza/bookie:${{ github.sha }}

      - name: Update GitOps repository
        run: |
          git clone https://${{ secrets.GITOPS_PAT }}@github.com/Baraziza/Bookie-GitOps.git
          cd Bookie-GitOps
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          sed -i "s|image: baraziza/bookie:.*|image: baraziza/bookie:${{ github.sha }}|" k8s-manifests/base/bookie/bookie-deployment.yaml
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push 